### ISSUE TITLE
IP Address of container is not reachable from the LAN computers

### ISSUE THREAD

**Issue by ebiancarelli** [ajkerrigan/crashplan-docker-synology#1]
_Thank you for your work!_ 
I'm hopeful this is more supportable vs the Patters synology packages that break monthly.

---

When I run the docker instance on my DS412+, it works great and can reach the CrashPlan online backup servers. The IP address of the docker instance is 172.17.0.1 (gateway: 172.17.42.1) and my lan subnet is 192.168.115.x. When the docker crash plan instance reports its info to the crash plan cloud, the 172 address is replicated to my LAN clients. This results is the LAN clients are not able to reach the docker instance.

Can I modify the docker network settings so that the docker container DHCPs on my network and treats the docker infrastructure as a bridge?

**Comment by ebiancarelli** [comment]
I stopped and restarted the container and not my LAN client can connect. I suppose it's using the public IP address?

**Comment by ghost** [comment]
Interesting, I was just popping in to thank you for testing and let you know that I was going to look into this. I haven't been running CrashPlan on my other LAN machines lately, since they've been in flux and the only stuff I actually care about is already on the NAS. Your issue prompted me to consider installing it on other LAN machines though, if for no other reason than to test connectivity. I'll definitely keep a closer eye on the networking side when I get some LAN backups going. If it's using the public IP, that's good and bad I guess. It'll work, but I don't want my LAN backup traffic going all over the internet and you probably don't either :).

In the meantime, I'm glad the issue seems to have not gotten in your way. And thanks for testing!

**Comment by ghost** [comment]
I checked this out a bit tonight. I still have some LAN testing to do but not sure when I'll get to it, so I'm reopening the issue. It's something I want to make sure I understand going forward.

To get back to your original question about using different docker settings - if you replace the `-h `hostname`` portion of `RUN_CMD` in the startup script with `--net=host`, the container will end up with the same IP as your NAS. You'll need to remove the existing container so it can be recreated with the new networking option. I'm not going to change the script here quite yet, but I've tested it successfully on my machine at least. If anything, it's one step closer to the networking setup you have when installing CrashPlan directly instead of using Docker.

**Comment by ebiancarelli** [comment]
`--net=host` absolutely worked perfectly for me. Thanks!
