### ISSUE TITLE
Synology md0 is running out of  space

### ISSUE THREAD

**Issue by gschepke** [ajkerrigan/crashplan-docker-synology#10]
The Docker-image is running smoothly on my DS412+, thanks for the fine work!

I tried to install the latest update. Unfortunately it failed due to a lack of space on the system volume md0.
So I used the command:
`/usr/bin/du -h -d 2 -x /usr/local/etc/`
which gave me the information that crashplan is using ca. 1g of space:
`12K     /usr/local/etc/crashplan/id`
`761M    /usr/local/etc/crashplan/cache`
`294M    /usr/local/etc/crashplan/log`
`80K     /usr/local/etc/crashplan/conf`
`20K     /usr/local/etc/crashplan/bin`
`1.1G    /usr/local/etc/crashplan`

Wouldn't it be a good idea to move this directory to /volume1 e.g. /volume1/crashplan/?
This volume is much bigger and will not interfere with any DSM-updates.

**Comment by ghost** [comment]
Hi there! Glad the image was working out well for you, and sorry to see you've hit some bumps. Seeing this issue reminded me that I ran into a space issue early on and changed to volume1 for my own installation. So good catch!

Shame on me for not documenting this properly back then, but I _think_ the reason I default to `/usr/local/etc/crashplan` is because that was the path used by my previous CrashPlan install (the third-party CrashPlan package from patters at PC Load Letter). I assume that most people who check out this repo are also switching from that package, so I try to keep that migration path relatively smooth. Keeping the same CrashPlan path allows this Docker setup to pick up where the PC Load Letter package left off, without having to go through a manual 'Adopt This Computer' step from the new CrashPlan.

In the short term, what may work to get you back up and running is something like this:
- Stop the container
- Migrate `/usr/local/etc/crashplan` to `/volume1/crashplan`
- Copy the [cp-user-vars.sh](https://github.com/ajkerrigan/crashplan-docker-synology/blob/master/cp-user-vars.sh) file to `/root/cp-user-vars.sh`
- Inside `/root/cp-user-vars.sh`, set `CRASHPLAN_DIR` to `/volume1/crashplan`
- Restart the container

In the longer term, I think some sort of interactive initial setup is probably a good way to go. I'm not sure when I'll have the time to properly dig into that. I don't want to overcomplicate things, but providing some guidance or tweaking default config values based on environment checks does seem valuable.

I hope this can at least help with your update issue, and get your backups running again. If you continue to have issues we can get them figured out together :). Feel free to continue the discussion here or jump on Gitter. Either way works for me, let me know how it goes!

**Comment by gschepke** [comment]
Hi,

Thank you very much for your fast answer and your hints :)

Unfortunately CrashPlan is still not running.

The file _crashplan/bin/vars.sh:_

SET APP_BASE_NAME=CrashPlan
SET APP_BASE_NAME_LOWER=crashplan
SET APP_DIR=/usr/local/crashplan
SET PRODUCT_CLASS=CONSUMER

had also a path leading to /usr/local.

I edited this.

Unfortunately I still get the error-message:

root@Geppetto:/# /usr/local/etc/rc.d/S99crashplandocker.sh start
Found the user variables file. Updating...
CRASHPLAN_DIR=/volume1/crashplan/crashplan
DATA_DIR=/volume1/CrashPlanBackups
USER_VOLUMES=-v /volume1:/volume1:ro
Starting CrashPlan container with ID 143e2e57c1e7.
_Error response from daemon: Cannot start container 143e2e57c1e7: stat
/usr/local/etc/crashplan: no such file or directory_
Error: failed to start containers: [143e2e57c1e7]

_/usr/local/etc/rc.d/S99crashplandocker.sh_

#!/bin/sh
#

# Startup script for running CrashPlan in a Docker container on a Synology

# NAS.

#

# AJ Kerrigan

DOCKER=/var/packages/Docker/target/usr/bin/docker
IMAGE=ajkerrigan/crashplan

# Pointing CRASHPLAN_DIR to an existing CrashPlan directory will allow

# the new container to take over for a previous installation, without

# the need to adopt the old computer.

# old - dir in base DSM dir !! CRASHPLAN_DIR="/usr/local/etc/crashplan"

_CRASHPLAN_DIR="/volume1/crashplan/crashplan"_

# Pointing DATA_DIR to an existing CrashPlan backup archive

# will allow the new instance of CrashPlan to skip a lot of time

# synchronizing the backup state.

DATA_DIR="/volume1/CrashPlan/backupArchives"

# Add/change entries here to suit your needs, for example:

# USER_VOLUMES="-v /volume1:/volume1:ro -v /photos:/photos:ro"

#

# The default setting will give the CrashPlan container read-only

# access to /volume1

USER_VOLUMES="-v /volume1:/volume1:ro"

# Check for overloaded variables in root's home dir

if [ -e /root/cp-user-vars.sh ]; then
   echo 'Found the user variables file. Updating...'
   . /root/cp-user-vars.sh
else
   echo 'No user variables file found. Using git defaults. You can change
the'
   echo 'default CrashPlan install directory, the user volumes, and data '
   echo 'directory by adding those variables to /root/cp-user-vars.sh'
fi

# Test

echo "CRASHPLAN_DIR=$CRASHPLAN_DIR"
echo "DATA_DIR=$DATA_DIR"
echo "USER_VOLUMES=$USER_VOLUMES"

# Test

VOLUMES="${USER_VOLUMES} -v ${CRASHPLAN_DIR}:/config -v ${DATA_DIR}:/data
-v /etc/localtime:/etc/localtime:ro"
PORTS="-p 4242:4242 -p 4243:4243"
RUN_CMD="${DOCKER} run -d --net=host --name=crashplan ${VOLUMES} ${PORTS}"
START_CMD="${DOCKER} start"
STOP_CMD="${DOCKER} stop"
PS_CMD="${DOCKER} ps --all --filter ancestor=${IMAGE}"

CONTAINER_ID=`${PS_CMD} --quiet`
[ ${CONTAINER_ID} ] && CONTAINER_STATUS=`${DOCKER} inspect
--format="{{.SynoStatus}}" ${CONTAINER_ID}`

_start ()
{
    if [ -z "${CONTAINER_ID}" ]; then
        echo "No existing CrashPlan container found. Running image
\"${IMAGE}\"."
        ${RUN_CMD} ${IMAGE}
    elif [ "${CONTAINER_STATUS}" == "exited" ]; then
        echo "Starting CrashPlan container with ID ${CONTAINER_ID}."
        ${START_CMD} ${CONTAINER_ID}
    else
        echo "Skipping start for CrashPlan container (ID ${CONTAINER_ID})
with \"${CONTAINER_STATUS}\" status."
    fi
}

_stop ()
{
    if [ -z "${CONTAINER_ID}" ]; then
        echo "Can't find a CrashPlan container to stop."
    elif [ "${CONTAINER_STATUS}" == "running" ]; then
        echo "Stopping CrashPlan container (ID ${CONTAINER_ID})."
        ${STOP_CMD} ${CONTAINER_ID}
    else
        echo "Skipping stop for CrashPlan container (ID ${CONTAINER_ID})
with \"${CONTAINER_STATUS}\" status."
    fi
}

_remove_container ()
{
    _stop
    if [ -n "${CONTAINER_ID}" ]; then
        echo "Removing CrashPlan container (ID ${CONTAINER_ID})."
        ${DOCKER} rm ${CONTAINER_ID} && unset CONTAINER_ID
    fi
}

_recreate()
{
    _remove_container
    _start
}

case $1 in
start)
    _start
    exit 0
    ;;

stop)
    _stop
    exit 0
    ;;

recreate)
    _recreate
    exit 0
    ;;

status)
    if [ -z "${CONTAINER_ID}" ]; then
        echo "No CrashPlan container found."
    else
        echo "
[[ Docker Container Status ]]

`${PS_CMD}`

[[ CrashPlan Service Information ]]
"
        awk -F ',' '{
            printf "%-15s %s\n%-15s %d\n%-15s %-15s\n\n",
            "Host",$3,
            "Port",$1,
            "Auth Token",$2
        }' ${CRASHPLAN_DIR}/id/.ui_info
        grep CPVERSION "${CRASHPLAN_DIR}/log/app.log"
    fi
    exit 0
    ;;

*)
    /bin/echo "Usage: $0 { start | stop | status | recreate }"
    exit 1
    ;;

esac

I don't have any clue where to find the remaining configuration line.

Thank you very much for you help.

Kind regards
Gunther

2016-05-27 3:47 GMT+02:00 AJ Kerrigan notifications@github.com:

> Hi there! Glad the image was working out well for you, and sorry to see
> you've hit some bumps. Seeing this issue reminded me that I ran into a
> space issue early on and changed to volume1 for my own installation. So
> good catch!
> 
> Shame on me for not documenting this properly back then, but I _think_
> the reason I default to /usr/local/etc/crashplan is because that was the
> path used by my previous CrashPlan install (the third-party CrashPlan
> package from patters at PC Load Letter). I assume that most people who
> check out this repo are also switching from that package, so I try to keep
> that migration path relatively smooth. Keeping the same CrashPlan path
> allows this Docker setup to pick up where the PC Load Letter package left
> off, without having to go through a manual 'Adopt This Computer' step from
> the new CrashPlan.
> 
> In the short term, what may work to get you back up and running is
> something like this:
> - Stop the container
> - Migrate /usr/local/etc/crashplan to /volume1/crashplan
> - Copy the cp-user-vars.sh
>   https://github.com/ajkerrigan/crashplan-docker-synology/blob/master/cp-user-vars.sh
>   file to /root/cp-user-vars.sh
> - Inside /root/cp-user-vars.sh, set CRASHPLAN_DIR to /volume1/crashplan
> - Restart the container
> 
> In the longer term, I think some sort of interactive initial setup is
> probably a good way to go. I'm not sure when I'll have the time to properly
> dig into that. I don't want to overcomplicate things, but providing some
> guidance or tweaking default config values based on environment checks does
> seem valuable.
> 
> I hope this can at least help with your update issue, and get your backups
> running again. If you continue to have issues we can get them figured out
> together :). Feel free to continue the discussion here or jump on Gitter.
> Either way works for me, let me know how it goes!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ajkerrigan/crashplan-docker-synology/issues/10#issuecomment-222040694,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASsEumeQI4Toj4zQUWbFmTWQ4eOnDo_tks5qFk0WgaJpZM4In1nf
> .

## 

Mit freundlichen Grüßen
Gunther Schepke

Email: gunther.schepke@gmail.com
Mobil: +49 172 87 89 156

**Comment by ghost** [comment]
Ah yes, should have seen that coming. The container volume mappings are set up during container creation, and future `start` operations don't change them.

Using `recreate` instead of `start` will kill the existing container and create a new one based on the same Docker image, using your updated volume paths. Please give that a shot when you get a chance. Thanks!

**Comment by gschepke** [comment]
Hi,
Thanks for the hint, I didn't dare to use _recreate_. It was not clear for
me whether I would loose my whole CrashPlan configuration.

I was necessary to start my CrashPlan-client twice.
After the first start it told me to be disconnected for 17 days (which is
certainly wrong) and terminated immediately.

After the next start, now everything seems to be ok.

Thanks a lot.

I wondered if the statement:

_# The default setting will give the CrashPlan container read-only_
_# access to /volume1_
_USER_VOLUMES="-v /volume1:/volume1:ro"_

wouldn't prevent CrashPlan from writing a log file?
But the timestamp of the file:
_/volume1/crashplan/crashplan/log/service.log.0_  is permanently changing,
obviously CrashPlan is running with sufficient rights :)

Thanks a lot for your support!

Kind regards
Gunther

2016-05-27 15:00 GMT+02:00 AJ Kerrigan notifications@github.com:

> Ah yes, should have seen that coming. The container volume mappings are
> set up during container creation, and future start operations don't
> change them.
> 
> Using recreate instead of start will kill the existing container and
> create a new one based on the same Docker image, using your updated volume
> paths. Please give that a shot when you get a chance. Thanks!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ajkerrigan/crashplan-docker-synology/issues/10#issuecomment-222140088,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASsEuqbfZByTexbdtFw1xtbMOx8e1P25ks5qFusEgaJpZM4In1nf
> .

## 

Mit freundlichen Grüßen
Gunther Schepke

Email: gunther.schepke@gmail.com
Mobil: +49 172 87 89 156

**Comment by ghost** [comment]
Great, glad it's ok now!

Your point about the read-only volume is interesting, because your setup (like mine) has host paths that map to multiple container volumes. In your case, you've got these mappings:

| Config Variable | Host Path | Container Path | Read-Only |
| --- | --- | --- | --- |
| USER_VOLUMES | /volume1 | /volume1 | Yes |
| CRASHPLAN_DIR | /volume1/crashplan/crashplan | /config | No |

Since both of those mappings include the host path `/volume1`, it means everything inside `CRASHPLAN_DIR` can be accessed two different ways inside the container. Taking your log file for example:

| Host Path | Container Path | Read-Only |
| --- | --- | --- |
| /volume1/crashplan/crashplan/log/service.log.0 | **/volume1/crashplan/crashplan**/log/service.log.0 | Yes |
| /volume1/crashplan/crashplan/log/service.log.0 | **/config**/log/service.log.0 | No |

Since the CrashPlan process writes to the `/config/log` directory, it works as expected. Hope that explains what's going on a little more clearly, it can definitely be confusing :).
