### ISSUE TITLE
Migrate from patters

### ISSUE THREAD

**Issue by unn** [ajkerrigan/crashplan-docker-synology#4]
Thanks for this repo. I was looking it over, and it seems to be missing instructions on how to migrate between Patters' package and your docker instance. Any advice?

**Comment by ghost** [comment]
Hi there! That's a documentation gap I'd like to fix. What _should_ work is stopping the patters package, then following the **Quick Start** section of the [README](https://github.com/ajkerrigan/crashplan-docker-synology/blob/master/README.md#quick-start).

There are some [customizable paths](https://github.com/ajkerrigan/crashplan-docker-synology/blob/master/README.md#customization), and as I recall I set up the default values so that they'd be a drop-in replacement for an existing patters installation. I'm not positive though - my migration started on a whim after being frustrated that CrashPlan died on me after an upgrade. I fiddled around a bit before I settled on something that I was happy with.

I'd be happy to work with you if you're up for it. In theory it'd be good for both of us - I'd feel a lot better having a documented and verified migration path from patters. I set up a [Gitter room](https://gitter.im/ajkerrigan/crashplan-docker-synology?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) so you or anyone else who's interested can kick around ideas.

**Comment by ruimarinho** [comment]
@ajkerrigan I'm finally migrating my Synology packages to Docker, so I'm starting with CrashPlan.  Coming from patters, here are some changes that should be considered and your input would be welcome:
- DATA_DIR: `/volume1/CrashPlan/backupArchives` is not the default dir on my installation. It is `/volume1/crashplan/backupArchives/` instead, but I'm not sure if I have tweaked this before.
- CRASHPLAN_DIR: `${CRASHPLAN_DIR}/id/.ui_info` does not exist. The files `.identity` and `.ui_info` sit under `/var/lib/crashplan/`, so the [grep](https://github.com/ajkerrigan/crashplan-docker-synology/blob/master/S99crashplandocker.sh#L145) command will fail.
- USER_VOLUMES: is this only used to backup files from?

**Comment by ghost** [comment]
- DATA_DIR: Thanks for letting me know about your path coming over from patters. I had paths with both capitalization styles on my NAS at different times, so I wasn't sure either. I'm OK switching to what you have (since I'm more confident in your path than mine honestly), and then updating in the future if someone raises an issue.
- CRASHPLAN_DIR: The `id` subfolder and two files inside it (`.identity` and `.ui_info`) will be created by the Docker container. The two files are recreated every time CrashPlan starts (in this case, that generally means anytime your NAS reboots or you manually restart the container).
- USER_VOLUMES: Yes, these are paths you want CrashPlan to be able to see so you can back them up. My backup settings when I switched from patters were all based on `/volume1` paths. I mount that path with the same name (read-only) inside the container, so the backup sets don't need any tweaking. As an alternative, you could mount volumes like `/homes`, `/photo`, etc separately and then redefine your backup sets. The way it's setup by default should be the path of least resistance from a working patters setup.

If you run into any issues with the migration, I hope we can work through them together and get them documented to help whoever else comes along. Thanks for helping to make this better.
